name = "network-api"
main = "src/index.ts"
compatibility_date = "2025-10-21"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding for SQLite
[[d1_databases]]
binding = "DB"
database_name = "network-db"
database_id = "8daa825c-f40c-4f62-8d88-d2d2877aa35b"

# KV for caching
[[kv_namespaces]]
binding = "CACHE"
id = "92150f9584de4309851ea09d1ad1b026"

# Durable Objects for WebSocket connections
[[durable_objects.bindings]]
name = "WEBSOCKET"
class_name = "WebSocketDurableObject"
script_name = "network-api"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketDurableObject"]

[vars]
JWT_SECRET = "your-secret-key-change-in-production"
JWT_EXPIRATION = "7d"
CORS_ORIGIN = "https://net.andernet.dev"

# For production, use secrets instead:
# wrangler secret put JWT_SECRET
# wrangler secret put UNIFI_API_KEY
